jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

#test
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:/config/fclover_prod/'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(82l93H2j8225rAfGelL3UcCrsZtUqlIXZ3QE/WPWnzs1aRS0s7H3rV4ow7RU0E/Id+BGVAcvqUYCTS7ZDPZQyUwgIdliVmtGC4vpSMTVBgDrj2AJdBJYtQDL4LVgInCqbrVjuzmLfQEGmp4I4h1U0g==)
            client-secret: ENC(J5KOkZtFtzsVYcJGz7uSPVm20txWwIGRUA2AzAg2nyipjFzOPkPfDGznNQ/qp2hXZ/UToo4zdlWJLPqXp2y0sbRZ6kOZzjZ7qStpEHV3HE4=)
            scope:
              - profile
              - email
          naver:
            client-id: ENC(8lpicoAlvXa3VOLlgvISDhvdiSwZ/Ezhoe2b41gdIbqkqZctCqbJkLnwJmLCdVXO8K4T3d7UyQuidNQ5wAGBdA==)
            client-secret: ENC(kpSclERDaSXREEGPaxEsDACUq6nnKaqV6pIlko7+urOX4uQnfIpK9AT5HwI9MpPn)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response


aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: fclover

cloud:
  aws:
    credentials:
      access-key:
      instance-profile: true
      secret-key: